### ISSUE TITLE
Can't select custom account

### ISSUE THREAD

**Issue by optim1stic** [nerdvibe/clorio-client#55]
Clorio 0.1.3. does not select a path to the wallet on a Ledger nano S (2.0.0). Always generated the 1st (44'/12586'/0'/0'0). 

v. 0.1.2 does not have such a problem

**Comment by iamnathanwindsor** [comment]
I have this problem too, I cannot select a custom derivation path with 0.1.3, and I could in previous versions. How can this be fixed? I cannot connect to a Ledger.

**Comment by nerdvibe** [comment]
Hi @optim1stic and @iamnathanwindsor I'm debugging on this issue. Currently mina-ledger-js does not support Ledger firmware >=2.0.0, but we are bringing the support to it soon.

I can confirm that with firmware < 2.0.0 the derivation path is generated correctly on Clorio 0.1.3/4.

@optim1stic are you saying that with Clorio 0.1.2 you can generate addresses different than 1? That's weird since the underlying library does not change the version between Clorio 0.1.2 and Clorio 0.1.3.

**Comment by nerdvibe** [comment]
We fixed this issue. Thank you for reporting.

To give a bit of context, this was not working with the desktop application, but on browser was working. The new release, which will be deployed in a few hours, will fix this issue.
